name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 150460248370.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t nginx-app .

    - name: Tag Docker image
      run: docker tag nginx-app:latest 150460248370.dkr.ecr.us-east-1.amazonaws.com/nginx-app:latest

    - name: Push Docker image
      run: docker push 150460248370.dkr.ecr.us-east-1.amazonaws.com/nginx-app:latest

    - name: Update Kubernetes manifest
      run: |
        git clone https://github.com/wcdennis/k8s-gitops-platform.git
        cd k8s-gitops-platform

        IMAGE_TAG=latest

        sed -i "s|image:.*nginx-app.*|image: 150460248370.dkr.ecr.us-east-1.amazonaws.com/nginx-app:${IMAGE_TAG}|g" apps/nginx/deployment.yaml

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add .
        git commit -m "Update image tag to latest"
        git push
